Traceback (most recent call last):
  File "/opt/ros/humble/lib/python3.10/site-packages/generate_parameter_library_py/parse_yaml.py", line 200, in __init__
    self.lang_str_value = func(default_value)
  File "/usr/lib/python3/dist-packages/typeguard.py", line 493, in wrapper
    check_argument_types(memo)
  File "/usr/lib/python3/dist-packages/typeguard.py", line 462, in check_argument_types
    raise TypeError(exc) from None
TypeError: type of argument "s" must be one of (NoneType, str); got list instead

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/humble/bin/generate_parameter_library_cpp", line 33, in <module>
    sys.exit(load_entry_point('generate-parameter-library-py==0.4.0', 'console_scripts', 'generate_parameter_library_cpp')())
  File "/opt/ros/humble/lib/python3.10/site-packages/generate_parameter_library_py/generate_cpp_header.py", line 66, in main
    run(output_file, yaml_file, validate_header)
  File "/opt/ros/humble/lib/python3.10/site-packages/generate_parameter_library_py/generate_cpp_header.py", line 45, in run
    gen_param_struct.parse(yaml_file, validate_header)
  File "/opt/ros/humble/lib/python3.10/site-packages/generate_parameter_library_py/parse_yaml.py", line 777, in parse
    self.parse_dict(self.namespace, doc[self.namespace], [])
  File "/opt/ros/humble/lib/python3.10/site-packages/generate_parameter_library_py/parse_yaml.py", line 884, in parse_dict
    self.parse_dict(key, root_map[key], nested_name)
  File "/opt/ros/humble/lib/python3.10/site-packages/generate_parameter_library_py/parse_yaml.py", line 890, in parse_dict
    self.parse_params(name, root_map, nested_name)
  File "/opt/ros/humble/lib/python3.10/site-packages/generate_parameter_library_py/parse_yaml.py", line 786, in parse_params
    ) = preprocess_inputs(self.language, name, value, nested_name_list)
  File "/opt/ros/humble/lib/python3.10/site-packages/generate_parameter_library_py/parse_yaml.py", line 698, in preprocess_inputs
    code_gen_variable = CodeGenVariable(
  File "/usr/lib/python3/dist-packages/typeguard.py", line 494, in wrapper
    retval = func(*args, **kwargs)
  File "/opt/ros/humble/lib/python3.10/site-packages/generate_parameter_library_py/parse_yaml.py", line 203, in __init__
    f'Parameter {param_name} has incorrect type. Expected: {defined_type}, got: {self.get_yaml_type_from_python(default_value)}'
  File "/opt/ros/humble/lib/python3.10/site-packages/generate_parameter_library_py/parse_yaml.py", line 216, in get_yaml_type_from_python
    return self.conversion.python_list_to_yaml_type[str(type(arg[0]))]
IndexError: list index out of range
gmake[2]: *** [CMakeFiles/three_omniwheel_controller_parameters.dir/build.make:71: include/three_omniwheel_controller/three_omniwheel_controller_parameters.hpp] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:139: CMakeFiles/three_omniwheel_controller_parameters.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
